server:
  port: 1011

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Undividedhl/springcloud-config.git
          search-paths: respo
          username:
          password:
      label: master

