server:
  port: 1011

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Undividedhl/springcloud-config.git
          search-paths: respo
          username:
          password:
      label: master

#springcloud007
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
